version: '3.4'

services:
  lanchonete.api:
    image: lanchoneteapi:dev
    build:
      target: base
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_lanchonete.api$
    volumes:
      - C:\_me\_projects\_lanchonete\Lanchonete\src\Services\Lanchonete.API:/app
      - C:\Users\fmendes\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_lanchonete.api$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_lanchonete.api$ bin/Debug/netcoreapp2.1/Lanchonete.API.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""
